# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('auteur', models.CharField(max_length=42)),
                ('checked', models.IntegerField(max_length=1)),
                ('contenu', models.TextField(null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de parution')),
                ('date_fin', models.DateTimeField(verbose_name='Echeance')),
            ],
        ),
    ]
