# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 21:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manapy', '0002_auto_20170726_2257'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Talk',
            new_name='Task',
        ),
    ]
