# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 22:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manapy', '0004_auto_20170726_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('auteur', models.CharField(max_length=42)),
                ('checked', models.IntegerField()),
                ('contenu', models.TextField(null=True)),
                ('categorie', models.CharField(max_length=100)),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('date_fin', models.DateTimeField(blank=True, null=True, verbose_name='Echeance')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('login', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=150)),
                ('rank', models.IntegerField()),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
            ],
        ),
        migrations.CreateModel(
            name='Users_Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasks_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manapy.Tasks')),
                ('users_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manapy.Users')),
            ],
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.AddField(
            model_name='tasks',
            name='users_tasts_id',
            field=models.ManyToManyField(through='manapy.Users_Tasks', to='manapy.Users'),
        ),
    ]
